language: python
python:
  - "2.7"
  - "3.8"
cache: pip
services:
  - docker

install:
  - pip install -U pip
  - pip --version
  - pip install tox tox-ansible
before_script:
  # Update submodules - like this one to get the latest
  - git submodule update --remote --recursive
  - cd ..
  # ansible collections need to be in an ansible_collection path
  - mkdir -p "ansible_collections/${COLLECTION_NAMESPACE}"
  - mv "$(basename "${TRAVIS_REPO_SLUG}")" "ansible_collections/${COLLECTION_NAMESPACE}/${COLLECTION_NAME}"
  - cd "ansible_collections/${COLLECTION_NAMESPACE}/${COLLECTION_NAME}"
script:
  - tox

env:
  global:
    - COLLECTION_NAMESPACE=devroles
    - COLLECTION_NAME=devel
    - TOX_ANSIBLE_DRIVER=docker
  jobs:
    - TOX_ANSIBLE_ROLE=ansible
    - TOX_ANSIBLE_ROLE=cinch
    - TOX_ANSIBLE_ROLE=mingw_sword_package
    - TOX_ANSIBLE_ROLE=sword

deploy:
  provider: releases
  api_key:
    secure: s1cFZ8mvo6wQfXxdmkPQA8hkOLsQHs3yFzUjGqGQ7L6eXcWTI9nsv3sD8Rp9kt8MK1Awd2mhF6pkygu2yCeuQgnzOXNZp0bjMDNIUnqjRkPKBJ/e3RSN3sXjvztdqpggpJ5UceLwcgsTOkMpmGwpVgIalKpP/tAPklSGro5FshpQFtIr2xR1zMWxuKg3bRjxgF74qvLvfgNwigpImGbTnxk0kf8r24qn/wwcY8gkCF97Sl2/oh5HYppqmjYmXpC2Mubo5szV4PXHLed/KlWtTF8sZiCKhTTe7uYoFGGbmKJE+SWltYG8RvPeaDicmbi+9zgm1qORXsEaBzB76AOvmdm8pF7v6F4IloymcGLREbprzoCB1XkA9F7/xDHQ4EnRX8gn96aIeS0tZ+6IQyJ51EBf0Up6ERSCSvya2MsSZvQS6OXYx7s0eoldoBWID2Pfowfv6a4VWzJc1atzg08/VRPq6A7RcJVQEwqTHNTQlZ+zPQ4kAuSx17joeDRu3qC0zsvPDgGPsWFyKq49i1kN1/UAPe5eK1B3C+raK564qmoP9QQ2mVH47ErqoENRUoYQVJz8tFBW/OqoW/Lo471180CzCugt4e3KYvKVwAi6vZ0TpYpx+5y1EloS/fBFlY3WpuaghJDKMJ6ZXDJprRPO8rWP3rgYw+ng3V0kMRhOcKk=
  file_glob: true
  file: "roles/mingw_sword_package/*.zip"
  skip_cleanup: true
  "on":
    repo: devroles/ansible_collection_devel
    tags: true
    condition: ${TOX_ANSIBLE_ROLE} = "mingw_sword_package"
    python: "3.8"
