language: python
python:
  - "2.7"
  - "3.8"
cache: pip
services:
  - docker

install:
  - pip install -U pip
  - pip --version
  - pip install tox tox-ansible
  - mkdir -p ~/.ssh  # Needed by authorized_key
  - touch ~/.ssh/id_rsa.pub

before_script:
  # Update submodules - like this one to get the latest
  - git submodule update --remote --recursive
  - cd ..
  # ansible collections need to be in an ansible_colection path
  - mkdir -p "ansible_collections/${COLLECTION_NAMESPACE}"
  - mv "$(basename "${TRAVIS_REPO_SLUG}")" "ansible_collections/${COLLECTION_NAMESPACE}/${COLLECTION_NAME}"
  - cd "ansible_collections/${COLLECTION_NAMESPACE}/${COLLECTION_NAME}"

script:
  - tox

env:
  global:
    - COLLECTION_NAMESPACE=devroles
    - COLLECTION_NAME=devel
    - TOX_ANSIBLE_DRIVER=docker
  jobs:
    - TOX_ANSIBLE_ROLE=ansible
    - TOX_ANSIBLE_ROLE=awx_devel
    - TOX_ANSIBLE_ROLE=cinch
    - TOX_ANSIBLE_ROLE=mingw_sword_package
    - TOX_ANSIBLE_ROLE=sword

#deploy:
#  provider: releases
#  api_key:
#    secure: nPjRqZBSgN0WzoF6go5sKE5lINSCs/bXzXGUlpdplgxYtgh31ZoLpB1kIb5/ugEeILtWIFeW4d18/PCmA5OpIJMeCFe0MzBVaFplWv7DuS3raWyZEIpNz+lkl0Kl5YWemmfylOhHOjggW6WlZ6zom1s5yAyCYvxE78oILm6tASsJ59FmdQY6AxawuiqyOxbzHgvFLPAOnp0h+rgGt+D1I9ZGq2HITIM/Kxzps7NOlWtSi5GshenYPW7Q5eJwUFAgdwfL8/RexwcI1QeivZJTh2/lNKXMmgYWnTr8joLHlczCMmzCXlzqV/DJ8bifxi+Mfd+SHbSqEanwAHvp6VwGtcaqHv0t0QICUOxRJC8aD80vPkx2M9dhXPhNDIGScDOvf0PP098bzJnkkpfrZ17O9wQMpCNs6MfE7vFgAKGK+3oBLJAnybvOHX8WNQAZ4iakRZl7c40wu0+3UPJdQSN8UKThe7vYESnCB4gBOVKHghXAJn128KCXaor53hfeqJhlKDQ6jEfTMcZOuTcyKpbVt/0Ih4rsBEljnMHz8vLxsozAdQ+4qCJ2W454J9Jo1+mdSfJGKDu6iIW2O8K6kYOErxeAVwMijciOEg3epiEGf+tMqKJaor2QWp+amnSWtW5GFHOHuIxCafK39BSoLymPHLhMCrSqanQIPw1U5ksA+3U=
#  file_glob: true
#  file: "*.zip"
#  skip_cleanup: true
#  "on":
#    repo: devroles/mingw_sword_package
#    tags: true
