galaxy_info:
  author: Greg Hellings
  description: >-
    Installs tools and packages to get a system ready for Java dev
  company: No one
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - all

dependencies: []
