galaxy_info:
  author: Greg Hellings
  description: >-
    Sets up a system to be ready for Fedora packaging
  company: No one
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - all

dependencies: []
