- name: install necessary packages
  become: true
  package:
    name: "{{ cinch_packages }}"
    state: present

- name: start and enable podman
  become: true
  service:
    name: podman
    state: started
    enabled: true
  when:
    - ansible_connection != 'docker'
    - ansible_connection != 'podman'

- name: check out code
  git:
    repo: https://github.com/RedHatQE/cinch
    dest: "{{ ansible_user_dir }}/cinch"
    version: master
  when: cinch_checkout_code
